//2021-12-26 KEEP for v1

import 'package:flutter/material.dart';
import 'package:moodclicks/screens/scrollcards.dart';
import 'package:moodclicks/services/createinitsurvey.dart';
import 'package:moodclicks/services/signup.dart';

class CreateSurvey extends StatefulWidget {
  const CreateSurvey({Key? key}) : super(key: key);

  @override
  _CreateSurveyState createState() => _CreateSurveyState();
}

class _CreateSurveyState extends State<CreateSurvey> {
  // late Survey surveyLocal;
  // late List<Survey> srv;
  // final loggedInUser = FirebaseAuth.instance.currentUser!.uid.toString();

  TextEditingController srvName = new TextEditingController();
  TextEditingController srvDescription = new TextEditingController();
  // TextEditingController id = new TextEditingController();
  // TextEditingController userId = new TextEditingController();
  @override
  Widget build(BuildContext context) {
    String emojiHeart = '\u2764';
    // Emoji smile = Emoji.fromJson(json)   ('Grinning Face');
    return Scaffold(
      appBar: AppBar(
        title: Text("1.1 createsurvey -  Menu Page" /*+ widget.searchstr*/),
        // actions: <Widget>[HomeNav()],
      ),
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Padding(
              padding: const EdgeInsets.all(34.0),
              child: TextButton(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      // builder: (BuildContext context) => PageViewDemo())); //Go Sample Cards
                      builder: (BuildContext context) => SignUp(),
                    ),
                  );
                  // print('${smile.name}');
                },
                child: Text(
                  emojiHeart + " Sign up and Create Survey",
                  style: TextStyle(fontSize: 18),
                ),
                // ),
              ),
            ),
            // INPUT FIELDS FOR NEW SURVEY
            // Padding(
            //   padding: const EdgeInsets.all(22.0),
            //   child: TextFormField(
            //     controller: srvName,
            //     decoration: InputDecoration(hintText: "Enter Survey Name:"),
            //   ),
            // ),
            // Padding(
            //   padding: const EdgeInsets.all(22.0),
            //   child: TextFormField(
            //     controller: srvDescription,
            //     decoration:
            //         InputDecoration(hintText: "Enter Survey Description"),
            //   ),
            // ),
            // SUBMIT BUTTON TO UPDATE AND CREATE
//             TextButton(
//               style: TextButton.styleFrom(primary: Colors.red),
//               onPressed: () async {
//                 // Generate a reference to a new location and add some data using push()
//                 var newPostRef = Navigator.push;
//                 String questionsAdded = "N";
// // Get the unique ID generated by push() by accessing its key
// // var postID = newPostRef.toString();
//                 final mySrv = Survey(
//                     name: srvName.text, description: srvDescription.text);
//                 // createSurvey();
//                 Map<String, dynamic> data = {
//                   "f00user": loggedInUser,
//                   // "f01name": srvName.text,
//                   // "f02description": srvDescription.text
//                   // "f03srvId": newPostRef.toString()
//                   "f01name": mySrv.name,
//                   "f02description": mySrv.description,
//                   "f03questionsexist": questionsAdded
//                 };
//                 FirebaseFirestore.instance.collection("survey").add(data);
//                 print(srvDescription.toString());
//                 print('\u{2764}');
//                 print(String.fromCharCode(0xdd25));
//                 print(String.fromCharCode(0xdd25));
//                 print(
//                   mySrv.description,
//                 );
//                 Navigator.push(
//                   context,
//                   MaterialPageRoute(
//                     builder: (BuildContext context) => AddQuestions(
//                         srvCreator: loggedInUser.toString()
//                         // final loggedInUser = FirebaseAuth.instance.currentUser!.uid.toString();
//                         // searchstr: searchstring.text,
//                         ),
//                   ),
//                 );
//               },
//               child: Text("Submit New Survey and Enter Survey Questions"),
//             ),
            SizedBox(
              height: 4,
            ),
            // Padding(
            //   padding: const EdgeInsets.all(34.0),
            //   child: TextButton(
            //     onPressed: () {
            //       Navigator.push(
            //         context,
            //         MaterialPageRoute(
            //           builder: (BuildContext context) => PageViewDemo(),
            //         ),
            //       ); //Go Sample Cards
            //       // builder: (BuildContext context) => SignUp()));
            //       // print('${smile.name}');
            //     },
            //     child: Text(
            //       emojiHeart + " View Sample Survey Display:",
            //       style: TextStyle(fontSize: 18),
            //     ),
            //     // ),
            //   ),
            // ),
            SizedBox(
              height: 10,
            ),
            // TextButton(
            //   onPressed: () {
            //     Navigator.push(
            //         context,
            //         MaterialPageRoute(
            //             // builder: (BuildContext context) => PageViewDemo())); //Go Sample Cards
            //             builder: (BuildContext context) => SignUp()));
            //     // print('${smile.name}');
            //   },
            //   child: Text(
            //     emojiHeart + " Heart Tfirst Survey :" + emojiHeart,
            //     style: TextStyle(fontSize: 24),
            //   ),
            //   // ),
            // ),
          ],
        ),
      ),
    );
  }

//   void createSurvey() {
//     Survey _newsurvey =         Survey(name: srvName.text, description: srvDescription.text);
//     print(srvDescription);
//   }
}
